### ISSUE TITLE
PianoText. Just sharing in case you don't know about it

### ISSUE THREAD

**Issue by iaeerfung** [alanxoc3/hatel#3]
http://annafeit.de/pianotext/
http://xahlee.info/kbd/piano_to_type_text.html

**Comment by alanxoc3** [comment]
Thanks for looking at this @iaeerfung. I actually did know about PianoText before I started this project. I follow her on twitter too. This layout is fundamentally different from PianoText though. It's geared more towards programmers and power users like me. Some thoughts:
- Every key is represented within the 12 note octave.
- One hand typing is easy, while alternating between two hands could theoretically double typing speed.
- No jumping around the piano, which means touch typing is much easier.
- This layout maps all letters, as well as all numbers and symbols too.
- Ctrl, alt, cmd, and shift are all supported. On my personal computer, I can currently technically do everything besides gaming with the piano, including using the mouse thanks to [keynav](https://github.com/jordansissel/keynav).
- There is no dependency on the pedal. You only need a midi keyboard with at least a full octave to be able to type everything.
- PianoText seems biased towards English, while Hatel is much more friendly to other languages.
- The vim navigation keys (jkhl) are all mapped to one key, which makes things like arrows easier.
- Hatel is better suited for metronome practice (as there is no pedal and there are no jumps).
- Partly because all letters & numbers are white keys (within the key of c), Hatel debatably sounds nicer than PianoText.

PianoText uses some shortcuts to try to make it faster, while hatel trys to provide more flexibility and functionality. Hatel aims at completely replacing my keyboard & mouse, while PianoText would be used in addition to your keyboard and mouse.

This project is in a very much alpha state and I'm the only user, but once I can type faster I'll publicize it more. ATM I consistently type 30-40 wpm excluding numbers/symbols with one hand. I'm between 20-30 if you include all numbers/symbols. I imagine I could at least double that if I practice alternating hands more. (Ex: to type "hello", left hand types "hlo" and right hand might type "el".)
